// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  mainSidebar: [
    'intro',
    'louisa-guide',
    {
      type: 'category',
      label: 'Architecture',
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: 'Setup',
      items: [{type: 'autogenerated', dirName: 'setup'}],
    },
    {
      type: 'category',
      label: 'Sync',
      items: [{type: 'autogenerated', dirName: 'sync'}],
    },
    {
      type: 'category',
      label: 'UAT',
      items: [{type: 'autogenerated', dirName: 'uat'}],
    },
    'troubleshooting',
    'glossary',
    'go-live-checklist',
    'changelog',
  ],
};

export default sidebars;
