name: Bug
description: Something isn't working
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened
    validations:
      required: true
  - type: textarea
    id: root-cause
    attributes:
      label: Root cause (if known)
    validations:
      required: false
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
    validations:
      required: false
